debug_info: /home/mathew/firmrebugger/binaries/P2IM/CNC/CNC.elf
interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x40000
  text:
    base_addr: 0x8000000
    file: ../data/CNC.bin
    permissions: r-x
    size: 0xd000
