interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: CNC.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1c4f4
symbols:
  0x0: s_lib_ver.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000189: __do_global_dtors_aux
  0x80001ad: frame_dummy
  0x80001f5: coolant_flood_on
  0x8000201: coolant_flood_off
  0x800020d: coolant_mist_on
  0x8000219: coolant_mist_off
  0x8000225: coolant_init
  0x800023d: coolant_stop
  0x800024d: coolant_run
  0x8000295: get_current_usecs
  0x80002cd: _delay_ms
  0x80002e3: _delay_us
  0x8000321: eeprom_init
  0x8000341: eeprom_get_char
  0x8000371: eeprom_put_char
  0x80003a5: memcpy_to_eeprom_with_checksum
  0x800041d: memcpy_from_eeprom_with_checksum
  0x80004a9: select_plane
  0x80004dd: gc_init
  0x800052d: gc_set_current_position
  0x800059d: to_millimeters
  0x80005e5: gc_execute_line
  0x80018d5: next_statement
  0x8001955: step_wr
  0x8001985: dirn_wr
  0x80019b5: limits_init
  0x80019ed: limits_isr
  0x8001a25: homing_cycle
  0x8001dd9: limits_go_home
  0x8001e69: grbl_main
  0x8001f21: mc_line
  0x8001f89: mc_arc
  0x8002499: mc_dwell
  0x8002555: mc_go_home
  0x800267d: mc_reset
  0x80026d1: read_float
  0x80028ad: delay_ms
  0x80028c1: delay_us
  0x80028d3: sys_sync_current_position
  0x8002909: next_block_index
  0x800292f: prev_block_index
  0x8002955: estimate_acceleration_distance
  0x80029a1: intersection_distance
  0x8002a11: max_allowable_speed
  0x8002a71: planner_reverse_pass_kernel
  0x8002b2d: planner_reverse_pass
  0x8002b91: planner_forward_pass_kernel
  0x8002c3d: planner_forward_pass
  0x8002cad: calculate_trapezoid_for_block
  0x8002e9d: planner_recalculate_trapezoids
  0x8002f71: planner_recalculate
  0x8002f85: plan_reset_buffer
  0x8002fb9: plan_init
  0x8002fd5: plan_discard_current_block
  0x8003009: plan_get_current_block
  0x8003041: plan_check_full_buffer
  0x8003069: plan_synchronize
  0x8003099: plan_buffer_line
  0x8003685: plan_set_current_position
  0x80036b1: plan_cycle_reinitialize
  0x8003735: printString
  0x800375d: printPgmString
  0x8003785: print_base2
  0x80037d3: print_uint8_base2
  0x80037ef: print_uint16_base2
  0x800380b: print_uint32_base10
  0x8003891: printInteger
  0x80038bb: printFloat
  0x8003a15: protocol_reset_line_buffer
  0x8003a35: protocol_init
  0x8003a51: protocol_execute_startup
  0x8003aa9: buttons_isr
  0x8003b05: protocol_execute_runtime
  0x8003c29: protocol_execute_line
  0x8003ef9: protocol_process
  0x8003ff1: report_status_message
  0x8004109: report_alarm_message
  0x8004161: report_feedback_message
  0x80041e9: report_init_message
  0x80041fd: report_grbl_help
  0x8004211: report_grbl_settings
  0x80044a9: report_gcode_parameters
  0x8004691: report_gcode_modes
  0x80048b1: report_startup_line
  0x80048f1: report_realtime_status
  0x8004b69: settings_store_startup_line
  0x8004b9d: settings_write_coord_data
  0x8004bd3: write_global_settings
  0x8004bf1: settings_reset
  0x8004cd5: settings_read_startup_line
  0x8004d25: settings_read_coord_data
  0x8004d7b: read_global_settings
  0x8004dd9: settings_store_global_setting
  0x800515d: settings_init
  0x80051b1: spindle_on
  0x80051bd: spindle_off
  0x80051c9: spindle_fwd
  0x80051d5: spindle_rev
  0x80051e1: spindle_init
  0x80051f9: spindle_stop
  0x8005205: spindle_run
  0x8005255: step_wr
  0x8005285: dirn_wr
  0x80052b5: stepper_motor_disable
  0x80052c1: stepper_motor_enable
  0x80052cd: set_step_events_per_minute
  0x8005309: iterate_trapezoid_cycle_counter
  0x8005349: step_period_isr
  0x8005709: step_pulse_isr
  0x8005721: step_delay_isr
  0x8005739: st_wake_up
  0x800578d: st_go_idle
  0x80057bd: st_reset
  0x80057e5: st_init
  0x8005805: st_cycle_start
  0x8005825: st_feed_hold
  0x8005849: st_cycle_reinitialize
  0x80058a9: serial_rx_hook
  0x8005921: aflCall
  0x8005929: startForkserver
  0x8005959: controlSanitizer
  0x800596d: HAL_Init
  0x80059b1: HAL_DeInit
  0x8005a09: HAL_MspInit
  0x8005a15: HAL_MspDeInit
  0x8005a21: HAL_IncTick
  0x8005a3d: HAL_GetTick
  0x8005a51: HAL_Delay
  0x8005a7b: HAL_GetHalVersion
  0x8005a8b: HAL_GetREVID
  0x8005aa1: HAL_GetDEVID
  0x8005ab9: HAL_EnableDBGSleepMode
  0x8005ad5: HAL_DisableDBGSleepMode
  0x8005af1: HAL_EnableDBGStopMode
  0x8005b0d: HAL_DisableDBGStopMode
  0x8005b29: HAL_EnableDBGStandbyMode
  0x8005b45: HAL_DisableDBGStandbyMode
  0x8005b61: HAL_EnableCompensationCell
  0x8005b79: HAL_DisableCompensationCell
  0x8005b91: NVIC_SetPriority
  0x8005be5: SysTick_Config
  0x8005c29: HAL_RCC_DeInit
  0x8005ca1: HAL_RCC_OscConfig
  0x8006141: HAL_RCC_ClockConfig
  0x80063c1: HAL_RCC_MCOConfig
  0x8006471: HAL_RCC_EnableCSS
  0x8006489: HAL_RCC_DisableCSS
  0x80064a1: HAL_RCC_GetSysClockFreq
  0x80065d9: HAL_RCC_GetHCLKFreq
  0x8006631: HAL_RCC_GetPCLK1Freq
  0x800667d: HAL_RCC_GetPCLK2Freq
  0x80066c9: HAL_RCC_GetOscConfig
  0x800686d: HAL_RCC_GetClockConfig
  0x80068cd: HAL_RCC_NMI_IRQHandler
  0x80068f5: HAL_RCC_CCSCallback
  0x8006901: NVIC_SetPriorityGrouping
  0x8006949: NVIC_GetPriorityGrouping
  0x8006965: NVIC_EnableIRQ
  0x8006995: NVIC_DisableIRQ
  0x80069c9: NVIC_GetPendingIRQ
  0x8006a09: NVIC_SetPendingIRQ
  0x8006a3d: NVIC_ClearPendingIRQ
  0x8006a71: NVIC_GetActive
  0x8006ab1: NVIC_SetPriority
  0x8006b05: NVIC_GetPriority
  0x8006b51: NVIC_EncodePriority
  0x8006bb5: NVIC_DecodePriority
  0x8006c21: NVIC_SystemReset
  0x8006c49: SysTick_Config
  0x8006c8d: HAL_NVIC_SetPriorityGrouping
  0x8006ca3: HAL_NVIC_SetPriority
  0x8006cdb: HAL_NVIC_EnableIRQ
  0x8006cf7: HAL_NVIC_DisableIRQ
  0x8006d13: HAL_NVIC_SystemReset
  0x8006d1f: HAL_SYSTICK_Config
  0x8006d37: HAL_NVIC_GetPriorityGrouping
  0x8006d45: HAL_NVIC_GetPriority
  0x8006d71: HAL_NVIC_SetPendingIRQ
  0x8006d8d: HAL_NVIC_GetPendingIRQ
  0x8006dab: HAL_NVIC_ClearPendingIRQ
  0x8006dc7: HAL_NVIC_GetActive
  0x8006de5: HAL_SYSTICK_CLKSourceConfig
  0x8006e1d: HAL_SYSTICK_IRQHandler
  0x8006e29: HAL_SYSTICK_Callback
  0x8006e35: HAL_GPIO_Init
  0x8007179: HAL_GPIO_DeInit
  0x80072b5: HAL_GPIO_ReadPin
  0x80072e3: HAL_GPIO_WritePin
  0x8007311: HAL_GPIO_TogglePin
  0x8007333: HAL_GPIO_EXTI_IRQHandler
  0x8007365: HAL_GPIO_EXTI_Callback
  0x8007379: gpio_clr
  0x80073ab: gpio_set
  0x80073dd: Error_Handler
  0x80073e3: SystemClock_Config
  0x8007475: debounce_on_handler
  0x80074cd: debounce_off_handler
  0x80074ed: main
  0x8007519: SystemInit
  0x8007575: SystemCoreClockUpdate
  0x8007669: gpio_toggle
  0x80076ab: NMI_Handler
  0x80076b7: HardFault_Handler
  0x80076bd: MemManage_Handler
  0x80076c3: BusFault_Handler
  0x80076c9: UsageFault_Handler
  0x80076cf: SVC_Handler
  0x80076db: DebugMon_Handler
  0x80076e7: PendSV_Handler
  0x80076f3: SysTick_Handler
  0x8007729: gpio_init
  0x80077ed: gpio_rd
  0x800781d: debounce_input
  0x800788d: debounce_rd
  0x80078c9: debounce_isr
  0x8007959: debounce_init
  0x8007979: NVIC_EnableIRQ
  0x80079a9: enable_tim_clock
  0x8007a09: enable_tim_interrupt
  0x8007a69: step_timer_init
  0x8007b09: step_isr_enable
  0x8007b5b: step_isr_disable
  0x8007b89: set_step_period
  0x8007bd9: set_step_pulse_delay
  0x8007bf7: set_step_pulse_time
  0x8007c15: TIM2_IRQHandler
  0x8007ca1: g540_timer_init
  0x8007d41: g540_timer_start
  0x8007d71: g540_timer_stop
  0x8007da1: timers_init
  0x8007db5: usart_putc
  0x8007de5: usart_flush
  0x8007df1: usart_tstc
  0x8007e1d: usart_getc
  0x8007e3d: enable_usart_clock
  0x8007eed: set_baud_rate
  0x8008129: usart_init
  0x80081dd: serial_init
  0x80081e9: serial_write
  0x8008203: __io_putchar
  0x800821f: serial_read
  0x8008253: serial_reset_read_buffer
  0x800826d: __aeabi_drsub
  0x8008275: __subdf3
  0x8008279: __aeabi_dadd
  0x80084f1: __floatunsidf
  0x8008511: __aeabi_i2d
  0x8008535: __aeabi_f2d
  0x8008571: __floatundidf
  0x8008581: __aeabi_l2d
  0x80085dd: __muldf3
  0x8008831: __divdf3
  0x8008a01: __gedf2
  0x8008a09: __ledf2
  0x8008a11: __nedf2
  0x8008a8d: __aeabi_cdrcmple
  0x8008a9d: __aeabi_cdcmpeq
  0x8008aad: __aeabi_dcmpeq
  0x8008ac1: __aeabi_dcmplt
  0x8008ad5: __aeabi_dcmple
  0x8008ae9: __aeabi_dcmpge
  0x8008afd: __aeabi_dcmpgt
  0x8008b11: __unorddf2
  0x8008b3d: __aeabi_d2iz
  0x8008b8d: __aeabi_d2uiz
  0x8008bcd: __truncdfsf2
  0x8008c6d: __aeabi_frsub
  0x8008c75: __aeabi_fsub
  0x8008c79: __addsf3
  0x8008dd9: __floatunsisf
  0x8008de1: __floatsisf
  0x8008dfd: __aeabi_ul2f
  0x8008e0d: __aeabi_l2f
  0x8008e89: __aeabi_fmul
  0x8008ff1: __aeabi_fdiv
  0x8009129: __gesf2
  0x8009131: __ltsf2
  0x8009139: __cmpsf2
  0x8009199: __aeabi_cfrcmple
  0x80091a1: __aeabi_cfcmpeq
  0x80091b1: __aeabi_fcmpeq
  0x80091c5: __aeabi_fcmplt
  0x80091d9: __aeabi_fcmple
  0x80091ed: __aeabi_fcmpge
  0x8009201: __aeabi_fcmpgt
  0x8009215: __aeabi_f2iz
  0x8009261: Reset_Handler
  0x8009268: CopyDataInit
  0x8009270: LoopCopyDataInit
  0x800927e: FillZerobss
  0x8009284: LoopFillZerobss
  0x80092b0: Default_Handler
  0x80092b1: DMA1_Stream3_IRQHandler
  0x80092b9: ceil
  0x80093d9: cos
  0x8009471: floor
  0x8009589: lround
  0x8009619: round
  0x80096b9: sin
  0x8009741: trunc
  0x80097ad: atan2
  0x80097b1: hypot
  0x8009865: sqrt
  0x8009921: __ieee754_atan2
  0x8009af5: __ieee754_hypot
  0x8009d39: __ieee754_rem_pio2
  0x800a17d: __ieee754_sqrt
  0x800a2f9: __kernel_cos
  0x800a541: __kernel_rem_pio2
  0x800add1: __kernel_sin
  0x800af41: atan
  0x800b285: fabs
  0x800b28d: finite
  0x800b299: matherr
  0x800b2a1: scalbn
  0x800b39d: copysign
  0x800b3ad: __errno
  0x800b3b9: __libc_init_array
  0x800b409: memset
  0x800b4a5: register_fini
  0x800b4b9: atexit
  0x800b4c5: __libc_fini_array
  0x800b4f9: __retarget_lock_acquire_recursive
  0x800b4fd: __retarget_lock_release_recursive
  0x800b501: __register_exitproc
  0x800b5c4: __EH_FRAME_BEGIN__
  0x800b5c5: _init
  0x800b5d1: _fini
  0x800b5dc: _etext
  0x800bcc4: APBAHBPrescTable
  0x800bcd4: gpio_info
  0x800be7c: npio2_hw
  0x800befc: two_over_pi
  0x800c008: PIo2
  0x800c048: init_jk
  0x800c058: atanhi
  0x800c078: atanlo
  0x800c098: _global_impure_ptr
  0x800c09c: __exidx_start
  0x800c0a0: __frame_dummy_init_array_entry
  0x800c0a4: __init_array_end
  0x800c0a8: _sidata
  0x800c4f4: _siccmram
  0x10000000: _sccmram
  0x20000000: _sdata
  0x20000004: AHBPrescTable
  0x20000014: __fdlib_version
  0x20000018: _impure_ptr
  0x20000020: impure_data
  0x20000448: __atexit_recursive_mutex
  0x2000044c: _edata
  0x20000450: object.8672
  0x20000468: current_coolant_mode
  0x2000046c: eeprom_ready
  0x20000470: eeprom_data
  0x20000870: block_buffer
  0x20000cf0: block_buffer_head
  0x20000cf1: block_buffer_tail
  0x20000cf2: next_buffer_head
  0x20000cf4: pl
  0x20000d10: line
  0x20000e10: char_counter
  0x20000e11: iscomment
  0x20000e12: current_direction
  0x20000e14: st
  0x20000e38: current_block
  0x20000e3c: step_bits
  0x20000e3e: dirn_bits
  0x20000e40: saved_step_bits
  0x20000e44: noHyperCall
  0x20000e48: uwTick
  0x20000e4c: limits_enabled
  0x20000e50: buttons_enabled
  0x20000e54: debounce
  0x20000e6c: debounce_ready
  0x20000e70: gc
  0x20000ea8: sys
  0x20000ebc: settings
  0x20000efc: __lock___atexit_recursive_mutex
  0x20000f00: __lock___arc4random_mutex
  0x20000f04: __lock___env_recursive_mutex
  0x20000f08: __lock___sinit_recursive_mutex
  0x20000f0c: __lock___malloc_recursive_mutex
  0x20000f10: __lock___at_quick_exit_mutex
  0x20000f14: __lock___dd_hash_mutex
  0x20000f18: __lock___tz_mutex
  0x20000f1c: __lock___sfp_recursive_mutex
  0x20000f20: __bss_end__
  0x2001ffff: _estack
