---
/home/mathew/firmrebugger/binaries/P2IM/CNC/CNC.bin: config/file-storage/c51ced249202ffc9/CNC.bin
hoedur_config.yml: config/file-storage/7b2a304e8d22c0b6/hoedur_config.yml
/home/mathew/firmrebugger/binaries/P2IM/CNC/CNC.elf: config/file-storage/f7d4a1a99f24a2a9/CNC.elf
